In [ ]:
import pandas as pd
data_path='https://storage.googleapis.com/kaggle-datasets/4305/6721/results.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1564156309&Signature=eynGlKo%2BETrk9VVk7KMaoM8Ek%2FHeVT25US%2BRLyfETjum8HuO8Cc1yVxnBJgDE0at%2BqHqxTE4AdtanDDDsQQexJv2aFhPqrGUYaQkJ9%2BeBme5mGsYeXa2D61IHQmWClkcgvIQdJm2tmpjf1QcI%2FYvoPER%2F4vbJ1TFX3OCJk2mn655gzON22sLqDOEPJNlVbMjtwEVUPBfRlWLQL1n23P48R66vxJcR1OkPU%2FRvPef4x7Busr8khuG6tagSV0HFhXoBpFnCu5oLxri8Zlghe5Xa%2BND1EvR0AbSF9Sr1rfZmimnjUksWmoiUd2aUz%2BZQ5ZywvV0OWx3YmFgSCN1VF6qrw%3D%3D'
data='https://storage.googleapis.com/kaggle-datasets/4305/6741/results.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1564162463&Signature=Ht2pRkqKS0YcaDsHGGwNVXhIyki0ftVXe6dr4h5iGd6QHsEzd1OttfbkaqOOqW6sv6mkVgk5upFIP8JtdB%2BfN1hdR%2Byq0w6VgO1j8VQ5j0Sw0iXg1waxY1fUt3cyR5HIgrvllulAzRdAoZNQE9yAWRsYLmWafeb8qiRhgfqck1fFGlLHZhSaLt%2BU6K2%2FZ9F%2FUhicy8Z4cYa9%2BrEgrkchc%2BsxmIQAatYY92vm5BF%2BZrArnMOMn8CLhlJk2BNpZDcAOZCmxYaczabK5BRO9riupg5UDJ0Yc7Yp1mkkO09QS62EWCupYT%2B%2Bw3vHehfTiYOkhtVhRVaMQquYqIZvxsiLJQ%3D%3D'
results = pd.read_csv(data)
results.head()

         date home_team away_team  ...  tournament     city   country
0  1872-11-30  Scotland   England  ...    Friendly  Glasgow  Scotland
1  1873-03-08   England  Scotland  ...    Friendly   London   England
2  1874-03-07  Scotland   England  ...    Friendly  Glasgow  Scotland
3  1875-03-06   England  Scotland  ...    Friendly   London   England
4  1876-03-04  Scotland   England  ...    Friendly  Glasgow  Scotland

[5 rows x 8 columns]

In [ ]:
results[(results["home_team"] =="Nigeria")|(results["away_team"] =="Nigeria")]

             date     home_team  ...                city               country
2978   1949-10-08  Sierra Leone  ...            Freetown          Sierra Leone
3051   1950-05-28         Ghana  ...                 NaN            Gold Coast
3220   1951-10-20       Nigeria  ...               Lagos               Nigeria
3495   1953-10-11         Ghana  ...               Accra            Gold Coast
3658   1954-10-30       Nigeria  ...               Lagos               Nigeria
3724   1955-05-28         Ghana  ...               Accra            Gold Coast
3800   1955-10-30         Ghana  ...               Accra            Gold Coast
3973   1956-10-06       Nigeria  ...               Lagos               Nigeria
3988   1956-10-27       Nigeria  ...               Lagos               Nigeria
4221   1957-10-27         Ghana  ...               Accra                 Ghana
4387   1958-10-25       Nigeria  ...               Lagos               Nigeria
4555   1959-11-08         Benin  ...             Cotonou               Dahomey
4560   1959-11-21         Ghana  ...               Accra                 Ghana
4562   1959-11-28       Nigeria  ...               Lagos               Nigeria
4635   1960-04-24          Togo  ...                 NaN                  Togo
4636   1960-04-26      Cameroon  ...                Lomé                  Togo
4664   1960-06-01          Mali  ...              Bamako       Mali Federation
4717   1960-08-28         Ghana  ...               Accra                 Ghana
4723   1960-09-10       Nigeria  ...               Lagos               Nigeria
4737   1960-10-02       Nigeria  ...               Lagos               Nigeria
4738   1960-10-02       Nigeria  ...               Lagos               Nigeria
4742   1960-10-05       Nigeria  ...                 NaN               Nigeria
4748   1960-10-09       Nigeria  ...               Lagos               Nigeria
4769   1960-10-29       Nigeria  ...               Lagos               Nigeria
4840   1961-04-08       Nigeria  ...               Lagos               Nigeria
4848   1961-04-22  Sierra Leone  ...            Freetown          Sierra Leone
4853   1961-04-30         Ghana  ...               Accra                 Ghana
4883   1961-06-01         Ghana  ...               Accra                 Ghana
4986   1961-11-25       Nigeria  ...               Lagos               Nigeria
5001   1961-12-10       Tunisia  ...               Tunis               Tunisia
...           ...           ...  ...                 ...                   ...
35860  2014-10-11         Sudan  ...            Khartoum                 Sudan
35924  2014-10-15       Nigeria  ...               Abuja               Nigeria
35992  2014-11-15         Congo  ...        Pointe-Noire                 Congo
36066  2014-11-19       Nigeria  ...                 Uyo               Nigeria
36121  2015-01-11       Nigeria  ...           Abu Dhabi  United Arab Emirates
36143  2015-01-17         Yemen  ...               Dubai  United Arab Emirates
36226  2015-03-25       Nigeria  ...                 Uyo               Nigeria
36287  2015-03-29  South Africa  ...           Nelspruit          South Africa
36461  2015-06-13       Nigeria  ...              Kaduna               Nigeria
36666  2015-09-05      Tanzania  ...       Dar es Salaam              Tanzania
36714  2015-09-08       Nigeria  ...       Port Harcourt               Nigeria
36750  2015-10-08       Nigeria  ...                Visé               Belgium
36806  2015-10-11       Nigeria  ...            Brussels               Belgium
36859  2015-10-17       Nigeria  ...       Port Harcourt               Nigeria
36874  2015-10-25  Burkina Faso  ...         Ouagadougou          Burkina Faso
36943  2015-11-13     Swaziland  ...             Lobamba             Swaziland
36992  2015-11-17       Nigeria  ...       Port Harcourt               Nigeria
37065  2016-01-18       Nigeria  ...              Kigali                Rwanda
37075  2016-01-22       Tunisia  ...              Kigali                Rwanda
37082  2016-01-26        Guinea  ...             Gisenyi                Rwanda
37171  2016-03-25       Nigeria  ...              Kaduna               Nigeria
37221  2016-03-29         Egypt  ...          Alexandria                 Egypt
37287  2016-05-27       Nigeria  ...   Le Petit-Quevilly                France
37321  2016-05-31    Luxembourg  ...          Luxembourg            Luxembourg
37595  2016-09-03       Nigeria  ...                 Uyo               Nigeria
37737  2016-10-09        Zambia  ...               Ndola                Zambia
37845  2016-11-12       Nigeria  ...                 Uyo               Nigeria
38022  2017-03-23       Nigeria  ...              London               England
38140  2017-06-01       Nigeria  ...  Saint-Leu-la-Forêt                France
38220  2017-06-10       Nigeria  ...                 Uyo               Nigeria

[535 rows x 8 columns]

In [ ]:
date=list(results['date'])
home_team=list(results['home_team'])
away_team=list(results['away_team'])
home_ft=list(results['home_ft'])
away_ft=list(results['away_ft'])
dates=[]
home_teams=[]
away_teams=[]
home_fts=[]
away_fts=[]
for count in range(len(date)):
  thedate=date[count]
  if int(thedate[0:4])>=2015:
    dates.append(date[count])
    home_teams.append(home_team[count])
    away_teams.append(away_team[count])
    home_fts.append(home_ft[count])
    away_fts.append(away_ft[count])

  elif int(thedate[0:4])==2014 and int(thedate[5:7])>=8:
    dates.append(date[count])
    home_teams.append(home_team[count])
    away_teams.append(away_team[count])
    home_fts.append(home_ft[count])
    away_fts.append(away_ft[count])

print(len(dates))
print(dates)
print(home_teams.index("Iran"))

2706

In [ ]:
countries=["Uruguay","Russia","Saudi Arabia","Egypt","Spain","Portugal","Iran","Morocco","France","Denmark","Peru","Australia","Croatia","Argentina","Nigeria","Iceland","Brazil","Switzerland","Serbia","Costa Rica","Sweden","Mexico","Korea Republic","Germany","Belgium","England","Tunisia","Panama","Colombia","Japan","Senegal","Poland"]
scores=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
matches=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
print(len(scores),len(countries),len(home_teams),len(dates),len(away_teams))

32 32 2706 2706 2706

In [ ]:
import math
table=list(rankings['Team'])
for num in range(len(dates)):
  team1=home_teams[num]
  team2=away_teams[num]
  proceed=False
  if team1=="Iran":
    rank1=table.index("IR Iran")
    proceed=True
  if team2=="Iran":
    rank2=table.index("IR Iran")
    proceed=True
  try:
    rank1=table.index(team1)+1
    rank2=table.index(team2)+1
    proceed=True
  except ValueError:
    pass
  if proceed==True:
   # m=math.log(rank1/rank2)
    m=rank1/rank2
   # m=201-abs(rank1-rank2)
    home=home_fts[num]
    away=away_fts[num]
    upd1=0
    upd2=0
    if home>away and m<1:
      upd1=3*(1+m)
      upd2=-3*m

    elif home>away and m>1:
      upd1=3/m
      upd2=-3/m

    elif away>home and m>1:
      upd1=-3*m
      upd2=3*(1+m)

    elif away>home and m<1:
      upd2=3*(1+1/m)
      upd1=-3/m

    elif home==away and m>1:
      upd2=1+1/m
      upd1=1/m

    elif home==away and m<1:
      upd1=1+1/m
      upd2=1/m
      
    else:
      print(home,away,team1,team2,dates[num],m,rank1,rank2)
      print("IMPOSSIBLE!")
      break
      
    update=False
    try:
        t1add=countries.index(team1)
        t2add=countries.index(team2)
        update=True
    except ValueError:
        pass
    if update==True:
      t1add=countries.index(team1)
      t2add=countries.index(team2)
      matches[t1add]=matches[t1add]+1
      matches[t2add]=matches[t2add]+1
      scores[t1add]=scores[t1add]+upd1
      scores[t2add]=scores[t2add]+upd2
      
      if team1=="Nigeria":
        print(upd1,team2,scores[t1add])
        
      if team2=="Nigeria":
        print(upd2,team1,scores[t2add])

3.357142857142857 Tunisia 3.357142857142857
0.978723404255319 Egypt 4.335866261398176
-2.9361702127659575 Egypt 1.3996960486322187
0.5957446808510638 Senegal 1.9954407294832825

In [ ]:
print(scores)
print(matches)

[47.518382352941174, -59.67048140265531, -8.029411764705882, -5.957777190432144, 6.285219179727376, 119.08796203796203, 11.544231350045303, 3.1824381926683714, 53.42029456051194, 2.4568605307735756, 7.53409090909091, -126.58235294117648, 10.600000000000001, 42.35924688057042, 1.9954407294832825, 7.1678321678321675, 221.49545454545455, -7.051282051282051, -36.098268398268395, 0.48475490196078397, 7.614379823075474, 48.63342245989304, -10.971679575237017, 137.0855311355311, 42.42954545454546, 57.32115384615384, 10.847619047619048, -8.236363636363636, 27.412045454545456, -84.41022408963586, 22.35040306594423, 25.787445887445887]
[11, 11, 6, 8, 10, 19, 4, 5, 21, 11, 8, 12, 7, 11, 4, 9, 14, 6, 8, 16, 10, 16, 9, 13, 8, 12, 11, 11, 13, 8, 6, 8]

In [ ]:
averages=[]
for index in range(0,len(scores)):
  averages.append(scores[index]/matches[index])
for l in range(0,32):
  print(countries[l]," : ",averages[l])

Uruguay  :  4.31985294117647
Russia  :  -5.42458921842321
Saudi Arabia  :  -1.338235294117647
Egypt  :  -0.744722148804018
Spain  :  0.6285219179727376
Portugal  :  6.267787475682212
Iran  :  2.8860578375113257
Morocco  :  0.6364876385336743
France  :  2.5438235505005684
Denmark  :  0.22335095734305233
Peru  :  0.9417613636363638
Australia  :  -10.548529411764706
Croatia  :  1.5142857142857145
Argentina  :  3.8508406255064016
Nigeria  :  0.49886018237082064
Iceland  :  0.7964257964257964
Brazil  :  15.821103896103896
Switzerland  :  -1.1752136752136753
Serbia  :  -4.512283549783549
Costa Rica  :  0.030297181372548998
Sweden  :  0.7614379823075474
Mexico  :  3.039588903743315
Korea Republic  :  -1.2190755083596685
Germany  :  10.545040856579316
Belgium  :  5.303693181818183
England  :  4.77676282051282
Tunisia  :  0.9861471861471862
Panama  :  -0.7487603305785124
Colombia  :  2.1086188811188813
Japan  :  -10.551278011204483
Senegal  :  3.725067177657372
Poland  :  3.223430735930736

In [ ]:
url='https://storage.googleapis.com/kaggle-datasets/31636/40571/Fixture.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1564157195&Signature=Syogoj3tnz4DxA4ylCC8fsuogBDOfeurFr3wjNHWBuXc7sdBFy0kyUaFO%2F2%2Fwgusa%2BDNP5hfZLQyHw3loT0a3MzsyS4C9qG5tpHZUZL6phgrMUoEy8eJZmMmId4GaSJtla9HU1tZstC0x6Cn8p1yiD5b4M9%2F9oBzALgkKToiwbSmjSe7iVrb9MGvjorvG9VVcrBDsMNJI%2FxEGVQ6llCq38vOeELPVIIz3IR%2FVsWi4e%2F3nlfBHLTIQtUyg0vjaCjoDc2y9yQEq3ThcpCrxOw6d4R2LxO7E85eeEtH9aQUnW0QO6hETjf9jDT85Ydy9IbYoWxioOdQ5F7qfDYuHH2HJg%3D%3D'
fixtures = pd.read_csv(url)
fixtures.head()

      Russia Saudi Arabia  0.0
0      Egypt      Uruguay  3.2
1    Morocco         Iran  0.0
2   Portugal        Spain  0.2
3     France    Australia  5.4
4  Argentina      Iceland  1.7

In [ ]:
url2='https://storage.googleapis.com/kaggle-datasets/31636/40571/Teams.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1564159456&Signature=GVi3f3meRPjanCk%2FT5KcAElv8NnNuFp6UOE9frcW5oDbJcPpTNUP9q68xSSMSX1K9u3Z%2Fc3mRvtO9p7pD4RAsDaJ0gmQ8B1dqUVZ%2BfBlfYL5%2BUzVkZMVvHfMVn5%2B7IteFeIkikCX7Hc6I5ChYx%2BWr1wfmufQ5F8OC36TzAArfM0qZCDP1YnHw1ztr5EfnatUNM0tMRU7nSkEwMvlsYcIwkJNNt5AHb4WoMX8Nkty9fWfzElbN463H2O2CscV5YUG4c97s3LjL38YbJuWDE6E3Hbn2Q%2BLnhNmXI6PCLZoT4ZuY6Ssfozzt9ekolkk2%2F9QbEKoxNJPtyiyc2adfEYZWQ%3D%3D'
rankings = pd.read_csv(url2)
rankings.head()

        Team  Points                                  Image
0    Germany    1544  //img.fifa.com/images/flags/4/ger.png
1     Brazil    1384  //img.fifa.com/images/flags/4/bra.png
2    Belgium    1346  //img.fifa.com/images/flags/4/bel.png
3   Portugal    1306  //img.fifa.com/images/flags/4/por.png
4  Argentina    1254  //img.fifa.com/images/flags/4/arg.png

In [ ]:
def quotient(x):
  rem=x%4
  x=x-rem
  return x/4

In [ ]:
countries[22]="South Korea"
groupA=[0,0,3,0]
groupB=[0,0,0,0]
groupC=[0,0,0,0]
groupD=[0,0,0,0]
groupE=[0,0,0,0]
groupF=[0,0,0,0]
groupG=[0,0,0,0]
groupH=[0,0,0,0]
t1=list(fixtures['Russia'])
t2=list(fixtures['Saudi Arabia'])
count=0
for number in range(len(t1)):
  count=count+1
  team_1=t1[number]
  team_2=t2[number]
  if team_1=="Columbia":
    team_1="Colombia"
  if team_2=="Columbia":
    team_2="Colombia"
  t1listpos=countries.index(team_1)
  t2listpos=countries.index(team_2)
  print(t1listpos,t2listpos)
  group=quotient(t1listpos)
  t1pos=t1listpos%4
  t2pos=t2listpos%4
  t1prob=round(averages[t1listpos])
  t2prob=round(averages[t2listpos])
  print(group,team_1,team_2,t1pos,t2pos,t1prob,t2prob)
  if t1prob>t2prob:
    if group==0:
      groupA[t1pos]=groupA[t1pos]+3
    elif group==1:
      groupB[t1pos]=groupB[t1pos]+3     
    elif group==2:
      groupC[t1pos]=groupC[t1pos]+3
    elif group==3:
      groupD[t1pos]=groupD[t1pos]+3
    elif group==4:
      groupE[t1pos]=groupE[t1pos]+3
    elif group==5:
      groupF[t1pos]=groupF[t1pos]+3
    elif group==6:
      groupG[t1pos]=groupG[t1pos]+3
    elif group==7:
      groupH[t1pos]=groupH[t1pos]+3
  elif t2prob>t1prob:
    if group==0:
      groupA[t2pos]=groupA[t2pos]+3
    elif group==1:
      groupB[t2pos]=groupB[t2pos]+3     
    elif group==2:
      groupC[t2pos]=groupC[t2pos]+3
    elif group==3:
      groupD[t2pos]=groupD[t2pos]+3
    elif group==4:
      groupE[t2pos]=groupE[t2pos]+3
    elif group==5:
      groupF[t2pos]=groupF[t2pos]+3
    elif group==6:
      groupG[t2pos]=groupG[t2pos]+3
    elif group==7:
      groupH[t2pos]=groupH[t2pos]+3
  elif t2prob==t1prob:
    if group==0:
      groupA[t2pos]=groupA[t2pos]+1
      groupA[t1pos]=groupA[t1pos]+1
    elif group==1:
      groupB[t2pos]=groupB[t2pos]+1 
      groupB[t1pos]=groupB[t1pos]+1
    elif group==2:
      groupC[t2pos]=groupC[t2pos]+1
      groupC[t1pos]=groupC[t1pos]+1
    elif group==3:
      groupD[t2pos]=groupD[t2pos]+1
      groupD[t1pos]=groupD[t1pos]+1
    elif group==4:
      groupE[t2pos]=groupE[t2pos]+1
      groupE[t1pos]=groupE[t1pos]+1
    elif group==5:
      groupF[t2pos]=groupF[t2pos]+1
      groupF[t1pos]=groupF[t1pos]+1
    elif group==6:
      groupG[t2pos]=groupG[t2pos]+1
      groupG[t1pos]=groupG[t1pos]+1
    elif group==7:
      groupH[t2pos]=groupH[t2pos]+1
      groupH[t1pos]=groupH[t1pos]+1
      
  else:
    print("IMPOSSIBLE")
  
 # if count==100:
  #  break

3 0
0.0 Egypt Uruguay 3 0 -1 4
7 6
1.0 Morocco Iran 3 2 1 3
5 4
1.0 Portugal Spain 1 0 6 1
8 11
2.0 France Australia 0 3 3 -11
13 15
3.0 Argentina Iceland 1 3 4 1
10 9
2.0 Peru Denmark 2 1 1 0
12 14
3.0 Croatia Nigeria 0 2 2 0
19 18
4.0 Costa Rica Serbia 3 2 0 -5
23 21
5.0 Germany Mexico 3 1 11 3
16 17
4.0 Brazil Switzerland 0 1 16 -1
20 22
5.0 Sweden South Korea 0 2 1 -1
24 27
6.0 Belgium Panama 0 3 5 -1
26 25
6.0 Tunisia England 2 1 1 5
31 30
7.0 Poland Senegal 3 2 3 4
28 29
7.0 Colombia Japan 0 1 2 -11
1 3
0.0 Russia Egypt 1 3 -5 -1
5 7
1.0 Portugal Morocco 1 3 6 1
0 2
0.0 Uruguay Saudi Arabia 0 2 4 -1
6 4
1.0 Iran Spain 2 0 3 1
8 10
2.0 France Peru 0 2 3 1
9 11
2.0 Denmark Australia 1 3 0 -11
13 12
3.0 Argentina Croatia 1 0 4 2
16 19
4.0 Brazil Costa Rica 0 3 16 0
14 15
3.0 Nigeria Iceland 2 3 0 1
18 17
4.0 Serbia Switzerland 2 1 -5 -1
24 26
6.0 Belgium Tunisia 0 2 5 1
23 20
5.0 Germany Sweden 3 0 11 1
22 21
5.0 South Korea Mexico 2 1 -1 3
25 27
6.0 England Panama 1 3 5 -1
29 30
7.0 Japan Senegal 1 2 -11 4
31 28
7.0 Poland Colombia 3 0 3 2
2 3
0.0 Saudi Arabia Egypt 2 3 -1 -1
0 1
0.0 Uruguay Russia 0 1 4 -5
6 5
1.0 Iran Portugal 2 1 3 6
4 7
1.0 Spain Morocco 0 3 1 1
11 10
2.0 Australia Peru 3 2 -11 1
9 8
2.0 Denmark France 1 0 0 3
15 12
3.0 Iceland Croatia 3 0 1 2
14 13
3.0 Nigeria Argentina 2 1 0 4
21 20
5.0 Mexico Sweden 1 0 3 1
22 23
5.0 South Korea Germany 2 3 -1 11
18 16
4.0 Serbia Brazil 2 0 -5 16
17 19
4.0 Switzerland Costa Rica 1 3 -1 0
29 31
7.0 Japan Poland 1 3 -11 3
30 28
7.0 Senegal Colombia 2 0 4 2
25 24
6.0 England Belgium 1 0 5 5
27 26
6.0 Panama Tunisia 3 2 -1 1

In [ ]:
print(groupA)
print(groupB)
print(groupC)
print(groupD)
print(groupE)
print(groupF)
print(groupG)
print(groupH)

[9, 0, 4, 4]
[1, 9, 6, 1]
[9, 3, 6, 0]
[6, 9, 0, 3]
[9, 3, 0, 6]
[3, 6, 0, 9]
[7, 7, 3, 0]
[3, 0, 9, 6]

In [ ]:
def winner(team1,team2):
  t1=round(averages[countries.index(team1)],1)
  t2=round(averages[countries.index(team2)],1)
  if t2>t1:
           return team2
  else:
           return team1
  
qualifier1=winner("France","Croatia")
qualifier2=winner("Uruguay","Iran")
qualifier3=winner("Brazil","Mexico")
qualifier4=winner("Belgium","Poland")
qualifier5=winner("Egypt","Portugal")
qualifier6=winner("Peru","Argentina")
qualifier7=winner("Costa Rica","Germany")
qualifier8=winner("Senegal","England")          
print(qualifier1,qualifier2,qualifier3,qualifier4,qualifier5,qualifier6,qualifier7,qualifier8)

France Uruguay Brazil Belgium Portugal Argentina Germany England

In [ ]:
semi1=winner(qualifier1,qualifier2)
semi2=winner(qualifier3,qualifier4)
semi3=winner(qualifier5,qualifier6)
semi4=winner(qualifier7,qualifier8)
print(semi1,semi2,semi3,semi4)

Uruguay Brazil Portugal Germany

In [ ]:
final1=winner(semi1,semi2)
final2=winner(semi3,semi4)
print(final1,final2)

Brazil Germany

In [ ]:
champion=winner(final1,final2)
print(champion)

Brazil